[FIX] partner_event: Don't update attendee_partner_id merging partners
Steps to reproduce:

- Have several partners with the same email.
- Generate an event registration for each of the partners.
- Launch the contact merge wizard.
- Select the destination contact the one with the name that is
  alphabetically later.
- Launch the merge.

Current behavior:

Model: Event Registration (event.registration), Constraint: event_registration_attendee_partner_id_fkey

ERROR: update or delete on table "res_partner" violates foreign key constraint "event_registration_attendee_partner_id_fkey" on table "event_registration"
DETAIL:  Key (id)=(NNN) is still referenced from table "event_registration"

Expected behavior:

Succesful merge.

The problem arises when ORM launches a flush before unlinking partners.
Such recomputation launches a write on existing event registration
records, which calls the update of the attendee_partner_id.

To prevent it, we just skip such process if performing the merge.

TT46798